### ISSUE TITLE
Not true speed being recorded

### ISSUE THREAD

**Issue by Nctrnluk** [saandhikaa/internet-speed-monitor#1]
HI there,

i have a gb connection and it showing 1.4mb/s......help?

**Comment by astronaut-symphony** [comment]
Hi Nctrnluk,

Thank you for bringing this to our attention. We've recently released an update (v1.1) that increases the maximum speed limit to 1Gbps (125MBps). This update should allow the Internet Speed Monitor to accurately reflect your gigabit connection speed.

Please update to the latest version (v1.1) and let us know if you continue to experience this issue.

Thank you.

**Comment by Nctrnluk** [comment]
Hi Mate,

Thank you for getting back to me - can you send a link to the new version?

**Comment by astronaut-symphony** [comment]
Ya, you can download the new version here. 

https://raw.githubusercontent.com/saandhikaa/internet-speed-monitor/main/assets/sandhika_net-speed_1.1.rmskin
